In [1]:
import pandas as pd
from glob import glob
import matplotlib.pyplot as plt

# === Load and combine all .xlsx files ===
xlsx_files = glob('../data/raw/*.xlsx')
dfs = [pd.read_excel(f) for f in xlsx_files]
df_combined = pd.concat(dfs, ignore_index=True)

# === Basic info ===
print(df_combined['label'].value_counts())
print(f"Total samples: {len(df_combined)}")
print("Columns available:", df_combined.columns.tolist())

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import numpy as np

# Simple approach: use raw features (no windowing yet)
feature_cols = ['p_ax','p_ay','p_az','p_gx','p_gy','p_gz',
                'a_ax','a_ay','a_az','a_gx','a_gy','a_gz']

X = df_combined[feature_cols].values
y = df_combined['label'].values

# Split: 80% train, 20% test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Train Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

# Check accuracy
accuracy = rf.score(X_test, y_test)
print(f"Accuracy: {accuracy * 100:.1f}%")

# Confusion matrix
from sklearn.metrics import confusion_matrix, classification_report
y_pred = rf.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


label
squat           5371
pushup          4006
jumping_jack    3075
Name: count, dtype: int64
Total samples: 12452
Columns available: ['time', 'p_ax', 'p_ay', 'p_az', 'p_gx', 'p_gy', 'p_gz', 'a_ax', 'a_ay', 'a_az', 'a_gx', 'a_gy', 'a_gz', 'label', 'reps']
Accuracy: 96.9%
              precision    recall  f1-score   support

jumping_jack       0.98      0.96      0.97       615
      pushup       0.97      0.96      0.97       801
       squat       0.96      0.99      0.97      1075

    accuracy                           0.97      2491
   macro avg       0.97      0.97      0.97      2491
weighted avg       0.97      0.97      0.97      2491

[[ 588    8   19]
 [   7  767   27]
 [   4   12 1059]]
